apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystones-deployment
  labels:
    app: keystones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keystones
  template:
    metadata:
      labels:
        app: keystones
    spec:
      containers:
      - name: keystones
        image: shedi/wowaudit:latest
        command: ["/srv/bin/refresh"]
        args: ["keystones"]

        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi

          limits:
            cpu: 1000m
            memory: 2000Mi

      imagePullSecrets:
        - name: regcred
