apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcl-deployment
  labels:
    app: wcl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wcl
  template:
    metadata:
      labels:
        app: wcl
    spec:
      containers:
      - name: wcl
        image: shedi/wowaudit:latest
        command: ["/srv/bin/refresh"]
        args: ["wcl"]

        resources:
          requests:
            cpu: 100m
            memory: 250Mi

          limits:
            cpu: 150m
            memory: 500Mi

      imagePullSecrets:
        - name: regcred
